spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: ${CLOUD.CONFIG.SERVER.GIT.URI}
          clone-on-start: true
          label: main
          username: ${CLOUD.CONFIG.SERVER.GIT.USERNAME}
          password: ${CLOUD.CONFIG.SERVER.GIT.PASSWORD}
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 8071

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVER_URL:http://discovery:8761}/eureka/